framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
            query.bus:
                middleware:
                    - validation
            event.bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: false
                    allow_no_senders: false
                middleware:
                    - validation
                    - 'App\Service\AmqpEventMapperMiddleware'

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Service\JsonAmqpSerializer
                options:
                    exchange:
                        name: quiz_events
                        type: topic
                    queues:
                        quiz.user.send_validation:
                            binding_keys: ['quiz.user.created']
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            'Quiz\Shared\Domain\Bus\Command': sync
            'Quiz\Shared\Domain\Bus\DomainEvent': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
