import styles from './layout.module.css'
import React from 'react'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main className={styles.container}>
      <div className={styles['session-card']}>
        <h2 className={styles.banner}>Quiz</h2>
        {children}
      </div>
    </main>
  )
}
