POST {{url}}/register
Content-Type: application/json
Accept: application/json

{
  "email": "{{user.email}}",
  "name": "{{user.name}}",
  "password": "{{user.password}}"
}

###

POST {{url}}/login
Content-Type: application/json
Accept: application/json

{
  "username": "{{user.email}}",
  "password": "{{user.password}}"
}

> {% client.global.set("auth_token", response.body.token); %}

###

GET {{url}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}
