parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/Symfony'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'
    Quiz\:
        resource: '../src/Quiz'

    acme_api.event.jwt_decoded_listener:
        class: App\EventListener\JWTCreatedListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
