user_creator:
  path: /register
  controller: Quiz\UserSession\Infrastructure\Controller\UserCreatorController
  methods: POST

user_password_updater:
  path: /user/{userId}/password
  controller: Quiz\UserSession\Infrastructure\Controller\UserPasswordUpdaterController
  methods: PUT
  requirements:
    userId: !php/const Symfony\Component\Routing\Requirement\Requirement::UUID_V4

user_email_verify:
  path: /user/verify/{token}
  controller: Quiz\UserEmailVerification\Infrastructure\Controller\EmailVerificationController
  methods: GET
  requirements:
    token: '\w{128}'
