import './globals.css'
import { SessionContextProvider } from '@/core/session/components/sessionContext'
import React from 'react'
import { Source_Code_Pro, DynaPuff } from 'next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const font = Source_Code_Pro({
  subsets: ['latin'],
  style: ['normal'],
  weight: ['400', '700'],
  variable: '--font-base',
})

const bannerFont = DynaPuff({
  subsets: ['latin'],
  style: ['normal'],
  weight: ['700'],
  variable: '--font-banner',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${font.variable} ${bannerFont.variable}`}>
        <SessionContextProvider>{children}</SessionContextProvider>
      </body>
    </html>
  )
}
